# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
puts 'seeding'

Product.create(title: 'Midnight 32', description: 'This little bag of awesomeness is one of sleek, dark looks. The jet black makes it stand out next to all other footbags!  It has 32 panels, pitch black synthetic suede fabric, and of course, metal filling. You won\'t ever regret getting your hands (or we should say feet) on one of these!', price: 1300, image: 'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/midnight-32-metal_940x.jpg?v=1626882161')
Product.create(title: 'BULLSEYE 62', description: 'The Bullseye 62 Panel Footbag is made with those with accuracy and longevity in mind. As with most of the larger panel count footbags, these will take some beating (with love) to break in completely, but once you get there, they are oh so sweet.', price: 1500, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/bullseye-62-plastic-1_940x.jpg?v=1626881853')
Product.create(title: 'NEMESIS 14', description: 'New to the world of footbags? Well, then this one’s for you! It\'s also for all you pro baggers out there... because that\'s just how awesome this footbag is. The Nemesis 14 is filled with sand, which gives it excellent stallability and pop; both at the same time! It\'s great for circles and even footbagging on your own. The Nemesis 14 Sand is just plain cool.', price: 1300, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/Nemesis-14-sand-1_10c2c83e-b97d-4e7d-b18a-600508fda5a7_470x.jpg?v=1626881980')
Product.create(title: 'SNOWBALL 12', description: 'Dragonfly Footbags is the premier brand of high quality, hand stitched footbags (hacky sacks) in the U.S. and abroad. We have been shipping Dragonfly Footbags from Elkhart, Indiana USA since 2003 to over 100 countries around the world and to every state in the US! Kick it high; kick it low – the Snowball 12 will show up no matter where you go. The all-white design makes the Snowball 32 ideal for almost every kind of playing condition (though maybe not in the snow). Filled with purified sand and hand stitched, the Snowball 32 is will easily become your favorite footbag.', price: 1800, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/snowball-32-sand-1_66902b9c-ec18-41c3-9933-bd5d7d18d10f_470x.jpg?v=1626882022')
Product.create(title: 'ASSASSIN 32', description: 'Boasting a 32 panel design, the Assassin is ideal for professionals seeking their personal best. Ideal for freestyling and stalling, the Assassin is a perfect combination of stability and pop. If you want to see what you are really made of, then the Assassin is the one footbag for you.', price: 1600, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/assassin-32-sand-2_600x.jpg?v=1630503315')
Product.create(title: 'FLAPJACK 62', description:'Great Googly Moogly, what are these odd-looking things? Well folks, they’re called Handsacks. What do you do with a handsack? THAT my friends, is a fair question. There are a few variations to the game out there (as there are for playing footbag) but essentially every part of your body that is legal playing footbag is legal in playing handsack. The additional dimension to the game is the use of the back of your hands for hitting and stalling. (great for younger kids and those who don’t consider themselves to be footbag pros) We could fill a few pages full of rules and tricks you can pull, but really what’s the fun in hand-feeding you all of that information? Go Google it!', price: 1900, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/Sand-2-Flapjack-Green_470x.jpg?v=1622654539')



Product.create(title: 'HITCH-HIKER 42', description: 'Somebody who can stay in control of virtually any situation is somebody who is said to know where his or her footbag is. The Hitchhiker 42 is that footbag and when in possession of yours, you will be able to attain the impossible, or at least improbable. But regardless what you face when using this magnificent footbag just remember, don’t panic. Also available with sand or pellet filling.', price: 2100, image: 'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/Hitchhiker-32-Plastic-Black-_-Red-1_470x.jpg?v=1631291214')
Product.create(title: 'SUNSPOT', description: 'The Sunspot was hand fabricated with the creative footbaggers in mind. With 32 panels, plastic filling, and 1-inch yellow tentacles, this baby will make you as bright as the sun! So suck it up, put your sunglasses on, and see what this hottie is capable of!', price: 2300, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/Sunspot-32-Black-_-Yellow-1_470x.jpg?v=1631291342')
Product.create(title: 'CHAINMAIL', description: 'A chainmail footbag is perfect when you need something a little more heavy duty for your kicking. This footbag (or hacky sack) is made from a unique combination of metal and rubber rings. Each one is handmade in the USA and is our unique design. No filling, just a bunch of perfectly interlocked rings give this bag the perfect combination of pop and stall.', price: 2600, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/light-blue-light-green-white-1_470x.jpg?v=1631290292')
Product.create(title: 'CLIPPER 24', description: 'The Clipper 24 panel footbag is now available with a metal filling. The same weight as the Clipper 24 Sand but filled with metal pellets for added control. If stalling is your thing, then the Clipper 24 is the right footbag for you. This bag was meant to perfect your stalling skills featuring 24 ultimate control panels. With its bright color scheme and excellent hand detailing, the Clipper 24 remains a footbag favorite.', price: 3200, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/clipper-24-metal_b22c8433-ff7f-4127-ae9e-e0b6fb45cd6e_470x.jpg?v=1620673460')
Product.create(title: 'HAIRBALL', description: 'Get ready for this unique design! The Hairball was handmade for your play in mind. With 32 panels, plastic filling, and 3-inch tentacles, this strange-looking thing is quite the footbag. Can you imagine how it gained its name?', price: 2100, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/Hair-Ball-32-Black-_-White-1_600x.jpg?v=1631291159')
Product.create(title: 'QUAD 4', description: 'The Quad allows for serious movement and stalls the low fill gives this bag the ultimate experience for all your tricks.', price: 3200, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/quad-4-metal_ad46b199-6ad1-45ae-ba6a-6461a185e27e_470x.jpg?v=1620673474')

Product.create(title: 'AMBER 8', description: 'From the creator: I have always loved the Dragonfly Footbag logo, and I have a huge fascination with fossils. So I thought I would try to marry the two together by designing a footbag that looks like it could be fossilized amber, with a Dragonfly inclusion suspended within it. Hence the name, The Amber. Of course I had to go with all metal fill (only because amber fill wasn’t an option)', price: 5100, image: 'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/amber-8-metal_a9f5dd24-9a27-41c5-8264-fd05e185c5f7_470x.jpg?v=1620673464')
Product.create(title: 'WHIRL 6', description: 'Metal filling makes this footbag a whirl to control and stall. The Whirl was created with stalling and freestyling in mind. Extra soft fabric makes tricks a lot easier to control, while still allowing for expert maneuvering. A bright color scheme makes the Whirl easy to watch no matter where you go. The world might start to spin when you use this footbag, but you’ll never lose track of the Whirl.', price: 2700, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/whirl-6-metal-1_6b4d6828-e0ee-401e-8577-208326c5ae5e_470x.jpg?v=1626882044')
Product.create(title: 'POGO 8', description: 'The Pogo allows for serious movement and stalls the low fill gives this bag the ultimate experience for all your tricks. The cork and metal filling is a unique combination that gives you a great balance of weight and control.', price: 2900, image:'https://cdn.shopify.com/s/files/1/0568/3419/5648/products/7_470x.jpg?v=1620919055')
puts 'done seeding'